name: Publish to maven and curseforge

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5.0.0
      - name: 'Set up JDK 21'
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 'Grant Permission to Gradle'
        run: chmod +x gradlew
      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@v4.4.3
      - name: 'License check with Gradle'
        run: ./gradlew checkLicenses
  compile:
    needs: license-check
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5.0.0
      - name: 'Set up JDK 21'
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 'Grant Permission to Gradle'
        run: chmod +x gradlew
      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@v4.4.3
      - name: 'Compile with Gradle'
        run: ./gradlew classes # Use classes instead of build to not make the test task redundant
  publish-maven:
    needs: compile
    runs-on: ubuntu-latest
    environment: Default
    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5.0.0
      - name: 'Set up JDK 21'
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 'Grant Permission to Gradle'
        run: chmod +x gradlew
      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@v4.4.3
      - name: 'Publish with Gradle'
        run: ./gradlew publish
  publish-curseforge:
    needs: compile
    runs-on: ubuntu-latest
    environment: Default
    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5.0.0
      - name: 'Set up JDK 21'
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 'Grant Permission to Gradle'
        run: chmod +x gradlew
      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@v4.4.3
      - name: 'Publish with Gradle'
        run: ./gradlew publishCurseForgePublicationToCurseForge
